/**
 * Product-related constants
 * This page holds the constants used across product components. used this instead of hardcoding values or using a database.
 * author: Dawid Pionk
 */


// Export all product constants
export const allProducts = [
   {
    id: 1,
    name: "Odessa Top",
    category: "Crochet",
    imageUrl: "./Crochet/the-odessa-top.png",
    description: "A cozy and stylish cardigan perfect for layering.",
    link: "https://www.instagram.com/p/C6_Btb0tXKH/?img_index=1",
  },
  {
    id: 2,
    name: "Lily Jane Cardigan",
    category: "Crochet",
    imageUrl: "./Crochet/lily-jane-cardigan.png",
    description: "A cozy and stylish cardigan perfect for layering.",
    link: "https://www.instagram.com/p/CuNSZVEr64H/?img_index=1",
  },
  {
    id: 3,
    name: "Tuesday Top",
    category: "Knit",
    imageUrl: "./Knit/tuesday-top.png",
    description: "A cozy and stylish cardigan perfect for layering.",
    link: "https://www.instagram.com/p/C6T8GwFtQ91/?img_index=1",
  },
  {
    id: 4,
    name: "Venus Dress",
    category: "Crochet",
    imageUrl: "./Crochet/the-venus-dress.png",
    description: "pattern out tomorrow!! really happy with how this dress came out :D pattern is beginner friendly and works up quicker than you think!! thank you @bugs.bundles for another lovely pattern <33",
    link: "https://www.instagram.com/p/C_Vljf6Na_Y/?img_index=1",
  },
  {
    id: 5,
    name: "Junebug Top",
    category: "Knit",
    imageUrl: "./Knit/junebug-top.png",
    description: "the first raglan i’ve enjoyed making and the keyhole detail is just so cute!! she works up quickly and is perfect for beginners!! pattern comes out friday :D by @natssrecord",
    link: "https://www.instagram.com/p/DBb-fTCuIfw/?img_index=1",
  },
  {
    id: 6,
    name: "Garden Tote Bag",
    category: "Crochet",
    imageUrl: "./Crochet/garden-tote-bag.png",
    description: "A cozy and stylish cardigan perfect for layering.",
    link: "https://www.instagram.com/p/Cs30iUNNXEE/?img_index=1",
  },
  {
    id: 7,
    name: "Garden Messenger Bag",
    category: "Crochet",
    imageUrl: "./Crochet/garden-messenger-bag.png",
    description: "A cozy and stylish cardigan perfect for layering.",
    link: "https://www.instagram.com/p/CuRgPQxLZMR/?img_index=1",
  },
  {
    id: 8,
    name: "Forest Fairy Leg Warmers",
    category: "Crochet",
    imageUrl: "./Crochet/forest-fairy-leg-warmers.png",
    description: "A cozy and stylish cardigan perfect for layering.",
    link: "https://www.instagram.com/p/CrEAZG3oG-i/?img_index=1",
  },
  {
    id: 9,
    name: "Diwata Dress",
    category: "Crochet",
    imageUrl: "./Crochet/diwata.png",
    description: "A cozy and stylish cardigan perfect for layering.",
    link: "https://www.instagram.com/p/C7HMbkQNWxb/?img_index=1",
  },
  {
    id: 10,
    name: "Camellia Cardigan",
    category: "Crochet",
    imageUrl: "./Crochet/camellia-cardigan.png",
    description: "A cozy and stylish cardigan perfect for layering.",
    link: "https://www.instagram.com/p/C7oK225tPLV/?img_index=1",
  },
  {
    id: 11,
    name: "Babydoll Top",
    category: "Crochet",
    imageUrl: "./Crochet/babydoll.png",
    description: "˚₊‧꒰ა ☆ ໒꒱ ‧₊˚ i cant wait to wear this all summer!!! babydoll crochet pattern by @natssrecords ✨",
    link: "https://www.instagram.com/p/DH8zvyxtIPC/?img_index=1",
  },
  {
    id: 12,
    name: "Leg Warmers",
    category: "Crochet",
    imageUrl: "./Crochet/leg-warmers.png",
    description: "A cozy and stylish cardigan perfect for layering.",
    link: "https://www.instagram.com/p/CubiFDvrNgp/?img_index=1",
  },
  {
    id: 13,
    name: "Zephyr Top",
    category: "Crochet",
    imageUrl: "./Crochet/the-zephyr-top.png",
    description: "A cozy and stylish cardigan perfect for layering.",
    link: "https://www.instagram.com/p/C8pHSHTtyW2/?img_index=1",
  },
  {
    id: 14,
    name: "Florence Cardigan",
    category: "Crochet",
    imageUrl: "./Crochet/florence-cardigan.png",
    description: "A cozy and stylish cardigan perfect for layering.",
    link: "https://www.instagram.com/p/C-3FnDpuN5v/?img_index=1",
  },
  {
    id: 15,
    name: "Garden Pond Tote",
    category: "Crochet",
    imageUrl: "./Crochet/the-garden-pond-tote.png",
    description: "A cozy and stylish cardigan perfect for layering.",
    link: "https://www.instagram.com/p/Cuz_IXHLXmJ/?img_index=1",
  },
  {
    id: 16,
    name: "Iris Top",
    category: "Knit",
    imageUrl: "./Knit/the-iris-top.png",
    description: "A cozy and stylish cardigan perfect for layering.",
    link: "https://www.instagram.com/p/C3zhVBIr-24/?img_index=1",
  },
  {
    id: 17,
    name: "Ophelia Top",
    category: "Knit",
    imageUrl: "./Knit/the-ophelia-top.png",
    description: "A cozy and stylish cardigan perfect for layering.",
    link: "https://www.instagram.com/p/CvhhxOxNpky/?img_index=1",
  }
];